spring:
  session:
    store-type: REDIS
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/webqq?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  http:
    encoding:
      enabled: true
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  data:
    mongodb:
      uri: mongodb://sso:841017@localhost:27017/sso
  redis:
    host: localhost
    password: 123456
    port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:config/mybatis-conf.xml

imooc:
  security:
    browser:
      signInResponseType: REDIRECT
      singInSuccessUrl: /im/chatRoom
      signInPage: /login
logging:
  level:
    com.ylz.imstomp.dao.mapper: debug
server:
  port: 8081
