spring:
  session:
    store-type: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/webqq?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  http:
    encoding:
      enabled: true
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672


server:
  port: 8090

imooc:
  security:
    browser:
      signInResponseType: REDIRECT
      singInSuccessUrl: /chatRoom
      signInPage: /login
